services:

  # template: 
  #   build:
  #     context: PATH_TO_DIR
  #   container_name: ${DJ_CONTAINER_NAME}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - rascendance-network
  #   ports:
  #     - ${BACKEND_PORT}:${BACKEND_PORT}
  #   expose:
  #     - ${POSTGRES_PORT}
  #   volumes:
  #     - ./PATH_TO_DIR/code:/code
  #   command: python /code/manage.py runserver 0.0.0.0:${BACKEND_PORT}
  # nginx:
  #  image: nginx:latest 
  #  container_name: ${NGINX_CONTAINER_NAME}
  #  env_file:
  #    - .env
  #  depends_on:
  #    - db

  nginx:
    build:
      context: nginx-files 
    container_name: ${NGINX_CONTAINER_NAME}
    env_file:
      - .env
    depends_on:
      - websocket
      - usermng
      - history
    volumes:
      - ./nginx-files/static-files:/etc/nginx/html
    ports:
      - 7000:443
    networks:
      - websocket-network
      - rascendance-network

  db:
    restart: always
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - rascendance-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      retries: 10
      timeout: 3s
      interval: 1s

  usermng:
    restart: always
    build:
      context: ./UserMng
      dockerfile: Dockerfile
    container_name: UserMng
    expose:
      - ${BACKEND_PORT}
    volumes:
      - ./UserMng/code:/UserMng/code
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DB_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER: ${DJANGO_SUPERUSER}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    networks:
      - rascendance-network

# match history
  history:
    restart: always
    build:
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    expose:
      - ${BACKEND_PORT}
    volumes:
      - ./history/code:/history/code
    depends_on:
      history-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_HISTORY}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DB_HISTORY_HOST}
      BACKEND_PORT: ${HISTORY_PORT}
    networks:
      - rascendance-network

  history-db:
    restart: always
    image: postgres:latest
    container_name: ${DB_HISTORY_HOST}
    volumes:
      - history_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_HISTORY}
    networks:
      - rascendance-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB_HISTORY}"]
      retries: 10
      timeout: 3s
      interval: 1s

# websocket

  websocket: 
    build:
      context: websocket
    container_name: ${WEBSOCKET_NAME}
    env_file:
      - .env
    depends_on:
      web-db:
        condition: service_healthy
    networks:
      - websocket-network
    expose:
      - ${WEBSOCKET_PORT}
    volumes:
      - ./websocket/code:/code
    command: python /code/manage.py runserver 0.0.0.0:${WEBSOCKET_PORT}

  redis:
    image: redis
    command: --port ${WS_REDIS_PORT}
    container_name: redis
    expose:
      -  ${WS_REDIS_PORT}
    networks:
      - websocket-network

  web-db:
    restart: always
    image: postgres:latest
    container_name: ${WS_DATABASE_NAME}
    volumes:
      - websocket_data:/var/lib/postgresql/data
    expose:
      - ${WS_DATABASE_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    networks:
      - websocket-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      retries: 10
      timeout: 3s
      interval: 1s

volumes:
  postgres_data:
    name: postgres_data
  websocket_data:
    name: websocket_data
  history_data:
    name: history_data

networks:
  rascendance-network:
    driver: bridge
  websocket-network:
    driver: bridge
