services:

  # template: 
  #   build:
  #     context: PATH_TO_DIR
  #   container_name: ${DJ_CONTAINER_NAME}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - rascendance-network
  #   ports:
  #     - ${BACKEND_PORT}:${BACKEND_PORT}
  #   expose:
  #     - ${POSTGRES_PORT}
  #   volumes:
  #     - ./PATH_TO_DIR/code:/code
  #   command: python /code/manage.py runserver 0.0.0.0:${BACKEND_PORT}
  
  nginx:
    image: nginx:latest 
    container_name: ${NGINX_CONTAINER_NAME}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_CONTAINER_NAME}
    networks:
      - rascendance-network

    env_file:
      - .env

volumes:
  postgres_data:

networks:
  rascendance-network:
    driver: bridge
