services:
#  web:
#    build:
#      context: .
#    container_name: ${DJ_CONTAINER_NAME}
#    env_file:
#      - .env
#    depends_on:
#      - db
  
  nginx:
    image: nginx:latest 
    container_name: ${NGINX_CONTAINER_NAME}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_CONTAINER_NAME}
    env_file:
      - .env

volumes:
  postgres_data:
