# Generated by Django 5.2 on 2025-04-10 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFA_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 4, 10, 14, 32, 4, 366053, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': '2FA_code',
                'verbose_name_plural': '2FA_codes',
                'ordering': ['timestamp'],
            },
        ),
    ]
