# Generated by Django 5.2 on 2025-04-09 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFactorAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofa_code',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 23, 6, 1, 382485, tzinfo=datetime.timezone.utc)),
        ),
    ]
