# Generated by Django 5.2 on 2025-04-10 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFactorAuth', '0003_alter_twofa_code_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofa_code',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 15, 3, 25, 361342, tzinfo=datetime.timezone.utc)),
        ),
    ]
