import { CanvasObject } from "./CanvasObject.js";
import { Counter } from "./Counter.js";
import { Ball } from "./Ball.js";
import { Player } from "./Player.js";
"use strict";

class Game {
/**
 * @param {JSON array} objs array generated by parsing the JSON with the config file
 */
constructor(objs) {	
	const canvas = document.getElementById("pong"); // TODO: pong o game? elegir nombre
	const context = canvas.getContext("2d");
	const game_objects = [];

	// TODO: valores por defecto a los valores que extraerá de config
	for (let i in objs) {
		switch (objs[i].type) {
		case "config":
			for(let j in objs[i])
				this[j] = objs[i][j];
			break;
		case "player":
			game_objects.push(new Player(objs[i], canvas, context));
			break;
		case "ball":
			game_objects.push(new Ball(objs[i], canvas, context));
			break;
		case "counter":
			game_objects.push(new Counter(objs[i], canvas, context));
			break;
		default:
			game_objects.push(new CanvasObject(objs[i], canvas, context));
		}
	}

	// TODO: sacar el tiempo de partida
	// TODO: sacar los puntos de partida
	// TODO: sacar color jugadores 1 y 2. Que cada jugador pueda jugar con los colores que desee
}

}