import { CanvasObject } from "./CanvasObject.js";
import { Counter } from "./Counter.js";
import { Ball } from "./Ball.js";
import { Player } from "./Player.js";
"use strict";

class Game {
/**
 * @param {JSON array} objs array generated by parsing the JSON with the config file
 */
constructor(objs) {	
	const game_objects = [];
	const game_config = [];
	let tmp;

	const canvas = document.getElementById("pong"); // TODO: pong o game? elegir nombre

	for (let i in objs) {
		switch (objs[i].type) {
		case "player":
			break;
		}
	}
}

}